# Generated by Django 3.2.10 on 2021-12-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'opportunity', 'verbose_name_plural': 'opportunities'},
        ),
    ]
