# Generated by Django 3.2.10 on 2021-12-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='upload_file',
            new_name='upload_book',
        ),
    ]
