# Generated by Django 3.2.10 on 2021-12-24 12:28

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
            },
        ),
        migrations.RenameModel(
            old_name='Director',
            new_name='Ceo',
        ),
        migrations.DeleteModel(
            name='TeamDescription',
        ),
    ]
