# Generated by Django 3.2.10 on 2021-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211224_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceo',
            name='content_four',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
