# Generated by Django 3.2.10 on 2021-12-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_ceo_content_four'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Media',
        ),
    ]
