# Generated by Django 3.2.10 on 2021-12-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_media_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'text', 'verbose_name_plural': 'text'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
    ]
