# Generated by Django 3.2.10 on 2021-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Preview',
                'verbose_name_plural': 'Preview',
            },
        ),
        migrations.AlterField(
            model_name='serviceone',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
