# Generated by Django 3.2.10 on 2021-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_products', '0002_auto_20211226_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impression',
            options={'verbose_name': 'impression', 'verbose_name_plural': 'impression'},
        ),
        migrations.AlterModelOptions(
            name='preview',
            options={'verbose_name': 'preview', 'verbose_name_plural': 'preview'},
        ),
        migrations.AlterField(
            model_name='serviceone',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='serviceone',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='serviceone',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
