# Generated by Django 3.2.10 on 2021-12-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_products', '0005_auto_20211226_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefive',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicefive',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicesix',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicesix',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
