# Generated by Django 3.2.10 on 2021-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_products', '0006_auto_20211226_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(upload_to='service_products/')),
            ],
            options={
                'verbose_name': 'service seven',
                'verbose_name_plural': 'service seven',
            },
        ),
        migrations.CreateModel(
            name='TitleTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'title two',
                'verbose_name_plural': 'title two',
            },
        ),
    ]
