# Generated by Django 3.2.10 on 2021-12-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_products', '0007_serviceseven_titletwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceseven',
            name='content',
        ),
    ]
