# Generated by Django 3.2.10 on 2021-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_products', '0008_remove_serviceseven_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='titletwo',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
