# Generated by Django 3.2.9 on 2021-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20211213_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='content',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='image',
        ),
        migrations.AddField(
            model_name='intro',
            name='content_one',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='intro',
            name='content_three',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='intro',
            name='content_two',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='intro',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='home_page/'),
        ),
        migrations.AddField(
            model_name='intro',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='home_page/'),
        ),
    ]
