# Generated by Django 3.2.10 on 2021-12-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20211224_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MidPageImage',
            new_name='MidImage',
        ),
    ]
