# Generated by Django 3.2.10 on 2021-12-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_rename_midpageimage_midimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midimage',
            options={'verbose_name': 'Mid_image', 'verbose_name_plural': 'Mid_image'},
        ),
        migrations.RenameField(
            model_name='headingthree',
            old_name='Customer_name',
            new_name='customer_name',
        ),
    ]
